RANDOM_SEED: 7102023
NUM_LABELS: 28
EMOTIONS:
    - admiration
    - amusement
    - anger
    - annoyance
    - approval
    - caring
    - confusion
    - curiosity
    - desire
    - disappointment
    - disapproval
    - disgust
    - embarrassment
    - excitement
    - fear
    - gratitude
    - grief
    - joy
    - love
    - nervousness
    - optimism
    - pride
    - realization
    - relief
    - remorse
    - sadness
    - surprise
    - neutral
definitions:
    admiration: "Finding something praiseworthy or deserving of utmost respect."
    amusement: "Experiencing a sense of delight or being entertained by something humorous."
    anger: "A powerful feeling of displeasure, hostility, or indignation."
    annoyance: "A mild form of vexation or irritation."
    approval: "Expressing a favorable judgment and recognizing its correctness."
    caring: "Exhibiting kindness, compassion, and concern for the well-being of others."
    confusion: "A state of perplexity, uncertainty, or lack of comprehension."
    curiosity: "An intense eagerness to acquire knowledge or uncover something new."
    desire: "A powerful longing or craving for something or a wish for a particular outcome."
    disappointment: "A feeling of dissatisfaction or sadness due to unmet hopes or expectations."
    disapproval: "Expressing disagreement, objection, and regarding something as unacceptable or inadequate."
    disgust: "A strong aversion or revulsion towards something deemed offensive or repugnant."
    embarrassment: "A feeling of self-consciousness, awkwardness, or discomfort in a particular situation."
    excitement: "A state of heightened enthusiasm, eagerness, or exhilaration."
    fear: "Experiencing a sense of apprehension, dread, or worry."
    gratitude: "A feeling of thankfulness, appreciation, or indebtedness."
    grief: "Profound sorrow or anguish, especially caused by the loss of a loved one."
    joy: "A state of profound delight, happiness, or elation."
    love: "A deep and tender affection or fondness for someone or something."
    nervousness: "A state of unease, apprehension, or anxiety."
    optimism: "A positive and hopeful outlook, expecting the best possible outcome."
    pride: "A feeling of self-respect, dignity, or satisfaction in one's achievements or those of others close to them."
    realization: "The act of becoming aware or comprehending a particular truth or situation."
    relief: "A sense of reassurance, comfort, or relaxation after a period of anxiety or distress."
    remorse: "A feeling of deep regret or guilt for one's actions or inactions."
    sadness: "A state of emotional pain, sorrow, or melancholy."
    surprise: "A sudden and unexpected feeling of astonishment or wonder."
    neutral: "No specific emotion or sentiment is expressed."